version: '3'
services:
  app:
    image: golang:1.18
    volumes:
      - /Users/meng/stu/go-docker:/go/src/examplecom/http_demo
    ports:
      - "8000:8080"
    command: go run /go/src/examplecom/http_demo/main.go