version: '3'
services:
  caddy:
    image: caddy
    restart: unless-stopped
    ports:
      - "8082:80"
      - "8082:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - /var/www/html/tico_web/dist:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
    external: true
  caddy_config: