version: "3"  # docker-compose版本
services:
  docker-python:
    build: .
    # image: "python:3.7.0b4"  # docker镜像名及版本
    hostname: docker-python-demo  # docker容器主机名
    container_name: docker-python-demo  # docker容器名
    volumes:  # 挂载目录
      - ./app:/app  # 项目相关
    # ports:  # 端口映射
    #   - "8000:8000"
    environment:  # 配置环境变量
      - TZ=Asia/Shanghai  # 设置时区
    network_mode: bridge  # 网络模式：host、bridge、none等，一般bridge