version: "3"
services:
  nginx:
    restart: always
    image: nginx
    restart: always
    user: root
    ports:
      - "9080:12345"
    volumes:
      - "$PWD/nginx/conf.d:/etc/nginx/conf.d"
      - "$PWD/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "/var/www/html/tico_web/dist:/usr/share/nginx/html"
      - ./log:/var/log/nginx/
    container_name: "proxy-intl-nginx"
    networks:
      - avatar
networks:
 avatar:
   external:
     name: avatar-net
