version: "3"
services:                            
  live:
    user: root
    restart: always             
    image: alfg/nginx-rtmp
    container_name: nginx-live          
    ports:                               
      - 8080:80
      - 1935:1935